export const skills = {
    "Arcana": {
        value: "Arcana",
        characteristic: "Brawn",
        rank: 0,
        max: 6,
        groupskill: false,
        careerskill: false,
        label: "GENEMON.SkillsNameArcana",
        abrev: "GENEMON.SkillsNameArcana",
        type: "Combat",
    },
    "Brawl": {
        value: "Brawl",
        characteristic: "Brawn",
        rank: 0,
        max: 6,
        groupskill: false,
        careerskill: false,
        label: "SWFFG.SkillsNameBrawl",
        abrev: "SWFFG.SkillsNameBrawl",
        type: "Combat",
    },
    "Initiative": {
        value: "Initiative",
        characteristic: "Brawn",
        rank: 0,
        max: 6,
        groupskill: false,
        careerskill: false,
        label: "GENEMON.SkillsNameInitiative",
        abrev: "GENEMON.SkillsNameInitiative",
        type: "Combat",
    },
    "Resilience": {
        value: "Resilience",
        characteristic: "Brawn",
        rank: 0,
        max: 6,
        groupskill: false,
        careerskill: false,
        label: "SWFFG.SkillsNameResilience",
        abrev: "SWFFG.SkillsNameResilience",
        type: "Combat",
    },
    "Resolve": {
        value: "Resolve",
        characteristic: "Brawn",
        rank: 0,
        max: 6,
        groupskill: false,
        careerskill: false,
        label: "GENEMON.SkillsNameResolve",
        abrev: "GENEMON.SkillsNameResolve",
        type: "Combat",
    },
};
